### ISSUE TITLE
Release v0.6.3

### ISSUE THREAD

**Issue by ajoubertza** [ska-sa/katcp-python#204]
This is just to inform users that a new minor release is planned. MeerKAT Control and Monitoring are the group most in need of this.

Task list:
- [x] Read steps in the How to Contribute docs for making a release
- [x] Edit the changelog and release notes files
- [x] Make sure Jenkins tests are still passing on master branch
- [x] Make sure the documentation is updated for master (readthedocs)
- [x] Create a release tag on GitHub, from master branch
- [x] Make sure the documentation is updated for release (readthedocs)
- [x] Upload the new version to PyPI
- [x] Fill the release description on GitHub
- [ ] Close this issue

**Comment by ludwigschwardt** [comment]
The one thing I just remembered about making the release tag on GitHub: make sure you pull it back to enable katversion to get the right version for building the tarball for PyPI. Because of that I still prefer doing the release tag afterwards. In the latest katdal release it allowed me to test out the deployment on testpypi first, find a bug and fix it while keeping the same version number :-)

**Comment by ludwigschwardt** [comment]
Also, setting the date in the changelog creates certain expectations and adds a sense of urgency to steps 3 to 7...

**Comment by ajoubertza** [comment]
v0.6.3 release completed.
